### PR TITLE
Add a bare-bones CLI for mozci

### PR DESCRIPTION
**Pull request by ahal**
This includes a simple 'mozci push tasks' subcommand that lists the
tasks that ran on a push along with their result.

### CODE REVIEW

**Review by marco-c — APPROVED** [review]
Thanks!

**Comment by marco-c** [comment]
It looks like mypy is failing. Can you add the typing stubs for the tabulate library?

**Comment by marco-c** [comment]
You can add them here https://github.com/mozilla/mozci/blob/535d2854ccf5c8f2e47709ce6664782d518ff716/.pre-commit-config.yaml#L66.

**Review by marco-c — APPROVED** [review]

**Comment by marco-c** [comment]
Oops, second time I approve without looking at the TC results :P

> mozci/console/application.py:0:1: C101 Coding magic comment not found
> mozci/console/commands/push.py:0:1: C101 Coding magic comment not found

@ahal could you fix that?

**Comment by ahal** [comment]
Weird.. these hooks and the mypy one get skipped when I commit locally. On a new computer.. wonder if I forgot to set something up properly.

**Comment by ahal** [comment]
Though, aren't the coding magic comments a vestige of Python 2 that are no longer necessary in Python 3? (Assuming the coding is utf-8?). I'm pretty sure we can remove this check.. though I'll fix it in this PR for now.

**Pull request merged**
